sonar.projectKey=naukri-automation-framework
sonar.projectName=Naukri Automation Framework
sonar.projectVersion=1.0

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes

sonar.junit.reportPaths=target/surefire-reports
sonar.jacoco.reportPaths=target/jacoco.exec
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.exclusions=**/test/**/*.java,**/*Test.java,**/*IT.java
sonar.test.exclusions=**/main/**/*.java

sonar.java.coveragePlugin=jacoco